#!/bin/bash

set -e

# Check to see if the job name is included.
if [[ $1 == "" ]]; then
  echo "Job Name Required"
  exit 1
fi

BASEDIR=$(dirname "$0")

# Check to see if the envionment file exists then source it
if [[ -f $BASEDIR/.env ]]; then
  source $BASEDIR/.env
fi

# Used to check if set.
get_env() {
    local output=""
    for var in "$@"
    do
        local val=${!var}
        if [[ "${val}" == "" ]]; then
            echo "$var variable not set"
            exit 1
        fi
        output="${output}-e ${var}=${val} "
    done
    echo "${output}"
}

# Check to see environment variables are set.
ENV_VARS=$(
  get_env \
  "COMPOSER_AUTH" \
  "DOCKERHUB_USER" \
  "DOCKERHUB_PASS" \
  "GITHUB_TOKEN" \
  "TERMINUS_TOKEN" \
  "USER_SSH_KEY" \
  "GIT_EMAIL" \
  "GIT_NAME"
)

CIRCLECI=$(which circleci || echo "")

# If CLI isn't installed
if [[ "$CIRCLECI" == "" ]]; then
  echo "CircleCI cli required. Install using the following instructions https://circleci.com/docs/2.0/local-cli/#installation"
fi

MAIN_CONFIG="${BASEDIR}/../.circleci/config.yml"
PROCESS_CONFIG="${BASEDIR}/process.yml"

$CIRCLECI config validate $MAIN_CONFIG
$CIRCLECI orb process $MAIN_CONFIG > $PROCESS_CONFIG
#$CIRCLECI local execute ${ENV_VARS} -c $PROCESS_CONFIG --job $1
$CIRCLECI build ${ENV_VARS} -c ${PROCESS_CONFIG} --job $1
