version: 2.1

# Run on Everything But Main Branch.
dev-filters: &dev-filters
  tags:
    ignore: /.*/
  branches:
    ignore:
      - main

# Run on everything but tags
non-tag-filters: &non-tag-filters
  tags:
    ignore: /.*/
  branches:
    only: /.*/

# Only Run On Tags
tag-filters: &tag-filters
  tags:
    only: /.*/
  branches:
    ignore: /.*/

# Run All the time
run-everytime: &run-everytime
  tags:
    only: /.*/
  branches:
    only: /.*/

orbs:
  ci-tools: kanopi/ci-tools@2
  orb-tools: circleci/orb-tools@12
  slack: circleci/slack@3.4.2

###########
### Workflows
###########
workflows:
  build_test:
    jobs:
      # Lint yml files to make sure formatted
      - orb-tools/lint:
          filters: *run-everytime

      # Pack Everything in src directory to orb.yml
      - orb-tools/pack:
          filters: *run-everytime

      # If is a branch publish dev version
      - orb-tools/publish:
          orb_name: kanopi/cms-updates
          filters: *run-everytime
          vcs_type: << pipeline.project.type >>
          dev_tags: dev:${CIRCLE_SHA1:0:7}
          requires:
            - orb-tools/lint
            - orb-tools/pack

      # If is a release publish version
      - orb-tools/publish:
          orb_name: kanopi/cms-updates
          pub_type: production
          vcs_type: << pipeline.project.type >>
          tag_pattern: '^[0-9]+\.[0-9]+\.[0-9]+$'
          post-steps:
            - slack/notify:
                title: "New Version of CMS Updates!!!!"
                message: "Kanopi CMS Update Orb has published new version: kanopi/cms-updates@${CIRCLE_TAG}"
                include_visit_job_action: false
                include_job_number_field: false
                include_project_field: false
          filters: *tag-filters
          requires:
            - orb-tools/lint
            - orb-tools/pack
