version: 2.1

orbs:
  cms-updates: kanopi/cms-updates@<<pipeline.parameters.dev-orb-version>>
  ci-tools: kanopi/ci-tools@1.10.0
  orb-tools: circleci/orb-tools@9.0.0
  slack: circleci/slack@3.4.2

# Pipeline Parameters
parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "1.0.0"

# Jobs
jobs:
  modify-default-value:
    executor: ci-tools/alpine
    steps:
      - checkout
      - ci-tools/install-yq
      - run:
          name: Modify Default Value
          command: |
            VERSION=${CIRCLE_SHA1:0:7} yq eval -i '.parameters.cms-updates-version.default = env(VERSION)' src/jobs/run-update.yml
      - persist_to_workspace:
          root: .
          paths:
            - src

###########
### Workflows
###########
workflows:
  build_test:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:

      # Modify the Value of the Current Version
      - modify-default-value

      # Lint yml files to make sure formatted
      - orb-tools/lint:
          checkout: false
          attach-workspace: true
          requires:
            - modify-default-value

      # Pack Everything in src directory to orb.yml
      - orb-tools/pack:
          checkout: false
          attach-workspace: true
          requires:
            - modify-default-value

      # If is a branch publish dev version
      - orb-tools/publish-dev:
          orb-name: kanopi/cms-updates
          requires:
            - orb-tools/lint
            - orb-tools/pack

      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          requires:
            - orb-tools/publish-dev
#          post-steps:
#            - slack/notify:
#                title: "New Dev Version of CMS Updates!!!!"
#                message: "Kanopi CMS Update Orb has published new dev version: kanopi/cms-updates@dev:${CIRCLE_SHA1:0:7}"
#                include_visit_job_action: false
#                include_job_number_field: false
#                include_project_field: false

  build_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - cms-updates/run-update:
          name: "COIT"
          executor: cms-updates/pantheon
          cms: "drupal"
          repo: "git@github.com:kanopi/coit-8"
          pr-branch: "main"
          docroot: "web"
          update-branch: "cms-updates/test"
          site-host: "pantheon"
          site-id: "coit-main"
          site-env: "live"
          update-method: "composer"

#      # If is a release publish version
#      - orb-tools/publish:
#          orb-ref: kanopi/cms-updates@${CIRCLE_TAG}
#          post-steps:
#            - slack/notify:
#                title: "New Version of CMS Updates!!!!"
#                message: "Kanopi CMS Update Orb has published new version: kanopi/cms-updates@${CIRCLE_TAG}"
#                include_visit_job_action: false
#                include_job_number_field: false
#                include_project_field: false
#          filters:
#            tags:
#              only: /[0-9]+\.[0-9]+\.[0-9]+/
#            branches:
#              ignore: /.*/
