version: 2.1

# Run on Everything But Main Branch.
dev-filters: &dev-filters
  tags:
    ignore: /.*/
  branches:
    ignore:
      - main

# Run on everything but tags
non-tag-filters: &non-tag-filters
  tags:
    ignore: /.*/
  branches:
    only: /.*/

# Only Run On Tags
tag-filters: &tag-filters
  tags:
    only: /.*/
  branches:
    ignore: /.*/

# Run All the time
run-everytime: &run-everytime
  tags:
    only: /.*/
  branches:
    only: /.*/


orbs:
  ci-tools: kanopi/ci-tools@1.10.0
  orb-tools: circleci/orb-tools@9.0.0
  slack: circleci/slack@3.4.2

# Jobs
jobs:
  modify-default-value:
    executor: ci-tools/alpine
    steps:
      - attach_workspace:
          at: .
      - ci-tools/install-yq
      - run:
          name: Modify Default Value
          command: |
            VERSION="\"${CIRCLE_SHA1:0:7}\"" yq eval -i '.jobs.run-update.parameters.cms-updates-version.default = env(VERSION)' orb.yml
      - persist_to_workspace:
          root: .
          paths:
            - orb.yml

###########
### Workflows
###########
workflows:
  build_test:
    jobs:
      # Lint yml files to make sure formatted
      - orb-tools/lint:
          filters: *run-everytime

      # Pack Everything in src directory to orb.yml
      - orb-tools/pack:
          filters: *run-everytime

      # Modify the Value of the Current Version
      - modify-default-value:
          filters: *run-everytime
          requires:
            - orb-tools/pack

      # If is a branch publish dev version
      - orb-tools/publish-dev:
          orb-name: kanopi/cms-updates
          filters: *run-everytime
          requires:
            - orb-tools/lint
            - modify-default-value

      # If is a release publish version
      - orb-tools/publish:
          orb-ref: kanopi/cms-updates@${CIRCLE_TAG}
          attach-workspace: true
          post-steps:
            - slack/notify:
                title: "New Version of CMS Updates!!!!"
                message: "Kanopi CMS Update Orb has published new version: kanopi/cms-updates@${CIRCLE_TAG}"
                include_visit_job_action: false
                include_job_number_field: false
                include_project_field: false
          filters: *tag-filters
          requires:
            - orb-tools/lint
            - modify-default-value