description: >
  Run WordPress Updates on Kinsta with WPCLI.
usage:
  version: 2.1
  orbs:
    cms-updates: kanopi/cms-updates@x.y.z
  workflows:
    automatic-updates:
      when:
        and:
          - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
          - equal: [ "automatic updates", << pipeline.schedule.name >> ]
      jobs:
        - cms-updates/run-update:
            cms: "wordpress"
            site-hosting: "kinsta"
            site-ip: "site-ip"
            site-user: "site-user"
            site-port: "site-port"
            update-method: "composer"
            context: content-name
