description: >
  Run Drupal 9 Updates on Pantheon with Composer.
usage:
  version: 2.1
  orbs:
    cms-updates: kanopi/cms-updates@x.y.z
  workflows:
    nightly_updates:
      triggers:
        - schedule:
            cron: "0 0 * * *"
            filters:
              branches:
                only:
                  - main
      jobs:
        - cms-updates/run-update:
            executor: cms-updates/pantheon
            cms: "drupal"
            docroot: "web"
            site-hosting: "pantheon"
            site-id: "site-machine-name"
            site-env: "live"
            update-method: "composer"
