description: >
  Run Drupal 9 Updates on Pantheon with Composer.
usage:
  version: 2.1
  orbs:
    cms-updates: kanopi/cms-updates@x.y.z
  workflows:
    automatic-updates:
      when:
        and:
          - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
          - equal: [ "automatic updates", << pipeline.schedule.name >> ]
      jobs:
        - cms-updates/run-update:
            cms: "drupal"
            docroot: "web"
            site-hosting: "pantheon"
            site-id: "site-machine-name"
            site-env: "live"
            update-method: "composer"
            context: context-name
